name: todo_client
version: 0.0.1

dependencies:
# pinning analyzer dependency to allow for pub resolution
  analyzer: ^0.27.3
  react: "^1.0.0"
  todo_sdk:
    git:
      url: git@github.com:Workiva/todo-example-sdk.git
  truss:
    hosted:
      name: truss
      url: https://pub.workiva.org
    version: "^2.8.1"
  w_flux: "^2.0.0"
  w_module: "^0.3.2"
  w_oauth2:
    hosted:
      name: w_oauth2
      url: https://pub.workiva.org
    version: "^1.2.0"
  w_session:
     hosted:
       name: w_session
       url: https://pub.workiva.org
     version: "^4.5.4"
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^0.3.2

dev_dependencies:
  browser: "^0.10.0"
  dart_dev: "^1.0.1"
  dart_style: "^0.2.0"
  test: "^0.12.0"
transformers:
  - web_skin_dart
  - test/pub_serve:
      $include: test/**_test{.*,}.dart