name: todo_client
version: 0.0.0

dependencies:
  react: "^0.8.0"
  todo_sdk:
    git:
      url: git@github.com:Workiva/todo-example-sdk.git
  truss:
    git:
      url: git@github.com:Workiva/truss.git
      ref: "0.6.0"
  uuid: "^0.5.0"
  w_flux: "^1.0.0"
  w_module: "^0.3.1"
  w_oauth2:
    git:
      url: git@github.com:Workiva/w_oauth2.git
      ref: "0.1.1"
  w_session:
    git:
      url: git@github.com:Workiva/w_session.git
      ref: "1.2.2"
  web_skin_dart:
    git:
      url: git@github.com:Workiva/web_skin_dart.git
      ref: "0.0.7"

dev_dependencies:
  browser: "^0.10.0"
  dart_dev: "^1.0.1"
  dart_style: "^0.2.0"
