name: todo_client
version: 0.0.1

dependencies:
  messaging_sdk:
    hosted:
      name: messaging_sdk
      url: https://pub.workiva.org
    version: ^2.7.1
  meta: ^1.0.5
  todo_sdk:
    git:
      url: git@github.com:Workiva/todo-example-sdk.git
      ref: 5351948d37bb59e71bd97b98fe7371eef4f37d6e
  truss:
    hosted:
      name: truss
      url: https://pub.workiva.org
    version: ^3.8.3
  w_flux: ^2.6.1
  w_module: ^1.2.1
  w_session:
     hosted:
       name: w_session
       url: https://pub.workiva.org
     version: ">=5.15.0 <7.0.0"
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^2.0.0

dev_dependencies:
  browser: ^0.10.0
  dart_dev: ^1.7.2
  dart_style: ^1.0.3
  dartdoc: ^0.12.0
  test: ^0.12.20
  mockito: ^2.0.0
  over_react_test: ^1.0.1
  w_test_tools:
    hosted:
      name: w_test_tools
      url: https://pub.workiva.org
    version: ^0.1.12

transformers:
  - web_skin_dart
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
