name: todo_example
version: 0.0.0

dependencies:
  messaging_sdk:
    path: ../messaging-sdk-dart
#    git:
#      url: git@github.com:Workiva/messaging-sdk-dart.git
#      ref: master
  react: "^0.8.0"
  todo_service:
    path: gen-dart/todo_service
  truss:
    git:
      url: git@github.com:Workiva/truss.git
      ref: "0.6.0"
  uuid: "^0.5.0"
  w_flux: "^1.0.0"
  w_module: "^0.3.1"
  w_oauth2:
    git:
      url: git@github.com:Workiva/w_oauth2.git
      ref: "0.1.1"
  web_skin_dart:
    git:
      url: git@github.com:Workiva/web_skin_dart.git
      ref: "0.0.7"

dev_dependencies:
  browser: "^0.10.0"
  dart_dev: "^1.0.1"
  dart_style: "^0.2.0"
  sass: any
  test: "^0.12.4"

dependency_overrides:
  messaging_frontend:
    path: ../messaging-frontend-dart

transformers:
- sass:
    executable: sass
