/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library base_service;

export 'src/status.dart' show Status;
export 'src/request_context.dart' show RequestContext;
export 'src/info.dart' show Info;
export 'src/health.dart' show Health;
export 'src/w_error.dart' show WError;
export 'src/base_service.dart' show BaseService;
export 'src/base_service.dart' show BaseServiceClient;
export 'src/base_service.dart' show BaseServiceProcessor;
