@TestOn('browser')
library test.unit.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit -e Environment.browser --genHtml`

import './components/app_test.dart' as components_app_test;
import './components/create_todo_input_test.dart' as components_create_todo_input_test;
import './components/edit_todo_modal_test.dart' as components_edit_todo_modal_test;
import './components/fab_toolbar_test.dart' as components_fab_toolbar_test;
import './components/todo_list_fab_test.dart' as components_todo_list_fab_test;
import './components/todo_list_test.dart' as components_todo_list_test;
import 'package:test/test.dart';
import 'package:react/react_client.dart';
import 'package:web_skin_dart/ui_core.dart';

void main() {
  setClientConfiguration();
  enableTestMode();
  components_app_test.main();
  components_create_todo_input_test.main();
  components_edit_todo_modal_test.main();
  components_fab_toolbar_test.main();
  components_todo_list_fab_test.main();
  components_todo_list_test.main();
}