@TestOn('browser')
library test.unit.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit -e Environment.browser --genHtml`

import 'package:test/test.dart';
import 'package:react/react_client.dart';
import 'package:web_skin_dart/ui_core.dart';

void main() {
  setClientConfiguration();
  enableTestMode();
}